### ISSUE TITLE
Feature Request: Mechanism for alternating lines 

### ISSUE THREAD

**Issue by demure** [nrosvall/memo#12]
I think it would be useful when viewing lists larger than ~6 lines, to have a way to easily keep track of what line you are on (at least when you need to use the note number to mark/delete).

The best method I can think of, without wasting screen space with '------' lines between notes, is allowing then user to use term colors to color/bold/reverse every other line. [example](https://stackoverflow.com/questions/16843382/colored-shell-script-output-library/16844327#16844327)

If this was added, I would likely try to use reverse grey on every other line, for minimal 'in-your-face' viewing.

**Comment by nrosvall** [comment]
Thanks. This is a great idea. Sometime ago I was wondering that something like this would be nice to have. I will look into it and implement something for v1.6.

**Comment by nrosvall** [comment]
I just released 1.6. There's something implemented to solve this issue. See the man page for information. In coming releases I will probably make improvements.

**Comment by demure** [comment]
Thanks for adding this.
Small note, colors currently don't play nicely with showing only undone notes
Again, thanks for making this program.

**Comment by nrosvall** [comment]
Ah, I will fix that today. Thanks!

**Comment by nrosvall** [comment]
Hmm actually it seems to be working for me. Do you mean running memo -u? What happens?

**Comment by demure** [comment]
Yes, with `memo -u` it seems to keep the full list's even/odd count.
[example](http://demure.sdf.org/posts/memo_color_undone_issue.png)

**Comment by nrosvall** [comment]
Ah. Yes it does. I did not think about that. I will change it so that it 
will count even/odd lines again for that. Same probably goes for memo -l 
<count>.

**Comment by nrosvall** [comment]
Ok, it took bit more work than I thought, but it's now fixed. Thanks for reporting the bug!
